### ISSUE TITLE
Values in PDF table containing | (pipe as a geometry) results in extra column

### ISSUE THREAD

**Issue by patatohead** [eadgyo/Extract-PDF-Excel#7]
Hello again, I run into a problem converting our PDF to Excel file.
When the PDF table contains a ' | ' (pipe) in its values, it creates an extra column. See image.
Is there an easy solution to prevent this?

![PDF2XLS](https://user-images.githubusercontent.com/79077157/130797921-783ffb53-bc6a-479e-b403-57ad80efcced.png)

**Comment by eadgyo** [comment]
Hello,
I have just looked into it. One possibility is that the character | is not
in the same direction with rest of text. You can otherwise send part of the
pdf which is not working, I can look more into it.

I have just added a new version, with the 3rd option being ignoreDirection
(by default it's false). So you can already try the hypothesis of
direction, by setting it to true (java -jar extractpdfexcel-0.1.jar
file.pdf out.excel true)

Eadgyo

**Comment by eadgyo** [comment]
https://github.com/eadgyo/Extract-PDF-Excel/releases/tag/extractExcelPdf_V0.1a

**Comment by eadgyo** [comment]
Possible evolution will be to add a clean up task, to remove unnecessary geometries or translate them to text, before running the extraction.
